root: true

extends:
  - pegasus

overrides:
  - files: '*.ts'
    extends:
      - pegasus/typescript
    parserOptions:
      project: tsconfig.eslint.json
  - files: 'tests/*.ts'
    rules:
      max-lines-per-function: off
