name: Tests

env:
  NODE_VERSION: 16

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: node --version
      - run: npm --version

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test
        env:
          NODE_ENV: test
